export const types = {
    // payments.controller - getPayments
    LIST_PAYMENTS: 'PAYMENTS/LIST/REQUEST',
    LIST_PAYMENTS_SUCCESS: 'PAYMENTS/LIST/SUCCESS',
    LIST_PAYMENTS_FAILURE: 'PAYMENTS/LIST/FAILURE',
    // payments.controller - getPaymentById
    GET_PAYMENTS: 'PAYMENTS/GET/REQUEST',
    GET_PAYMENTS_SUCCESS: 'PAYMENTS/GET/SUCCESS',
    GET_PAYMENTS_FAILURE: 'PAYMENTS/GET/FAILURE',
    // payments.controller - createPayment
    CREATE_PAYMENTS: 'PAYMENTS/CREATE/REQUEST',
    CREATE_PAYMENTS_SUCCESS: 'PAYMENTS/CREATE/SUCCESS',
    CREATE_PAYMENTS_FAILURE: 'PAYMENTS/CREATE/FAILURE',
    // payments.controller - updatePayment
    UPDATE_PAYMENTS: 'PAYMENTS/UPDATE/REQUEST',
    UPDATE_PAYMENTS_SUCCESS: 'PAYMENTS/UPDATE/SUCCESS',
    UPDATE_PAYMENTS_FAILURE: 'PAYMENTS/UPDATE/FAILURE'
};
