export const types = {
    // rooms.controller - getRooms
    LIST_ROOMS: 'ROOMS/LIST/REQUEST',
    LIST_ROOMS_SUCCESS: 'ROOMS/LIST/SUCCESS',
    LIST_ROOMS_FAILURE: 'ROOMS/LIST/FAILURE',
    // rooms.controller - getRoomById
    GET_ROOMS: 'ROOMS/GET/REQUEST',
    GET_ROOMS_SUCCESS: 'ROOMS/GET/SUCCESS',
    GET_ROOMS_FAILURE: 'ROOMS/GET/FAILURE',
    // rooms.controller - createRoom
    CREATE_ROOMS: 'ROOMS/CREATE/REQUEST',
    CREATE_ROOMS_SUCCESS: 'ROOMS/CREATE/SUCCESS',
    CREATE_ROOMS_FAILURE: 'ROOMS/CREATE/FAILURE',
    // rooms.controller - updateRoom
    UPDATE_ROOMS: 'ROOMS/UPDATE/REQUEST',
    UPDATE_ROOMS_SUCCESS: 'ROOMS/UPDATE/SUCCESS',
    UPDATE_ROOMS_FAILURE: 'ROOMS/UPDATE/FAILURE'
};
