export const types = {
    // guests.controller - getGuests
    LIST_GUESTS: 'GUESTS/LIST/REQUEST',
    LIST_GUESTS_SUCCESS: 'GUESTS/LIST/SUCCESS',
    LIST_GUESTS_FAILURE: 'GUESTS/LIST/FAILURE',
    // guests.controller - getGuestById
    GET_GUESTS: 'GUESTS/GET/REQUEST',
    GET_GUESTS_SUCCESS: 'GUESTS/GET/SUCCESS',
    GET_GUESTS_FAILURE: 'GUESTS/GET/FAILURE',
    // guests.controller - createGuest
    CREATE_GUESTS: 'GUESTS/CREATE/REQUEST',
    CREATE_GUESTS_SUCCESS: 'GUESTS/CREATE/SUCCESS',
    CREATE_GUESTS_FAILURE: 'GUESTS/CREATE/FAILURE',
    // guests.controller - updateGuest
    UPDATE_GUESTS: 'GUESTS/UPDATE/REQUEST',
    UPDATE_GUESTS_SUCCESS: 'GUESTS/UPDATE/SUCCESS',
    UPDATE_GUESTS_FAILURE: 'GUESTS/UPDATE/FAILURE'
};
