export const types = {
    // bookings.controller - getBookings
    LIST_BOOKINGS: 'BOOKINGS/LIST/REQUEST',
    LIST_BOOKINGS_SUCCESS: 'BOOKINGS/LIST/SUCCESS',
    LIST_BOOKINGS_FAILURE: 'BOOKINGS/LIST/FAILURE',
    // bookings.controller - getBookingById
    GET_BOOKINGS: 'BOOKINGS/GET/REQUEST',
    GET_BOOKINGS_SUCCESS: 'BOOKINGS/GET/SUCCESS',
    GET_BOOKINGS_FAILURE: 'BOOKINGS/GET/FAILURE',
    // bookings.controller - createBooking
    CREATE_BOOKINGS: 'BOOKINGS/CREATE/REQUEST',
    CREATE_BOOKINGS_SUCCESS: 'BOOKINGS/CREATE/SUCCESS',
    CREATE_BOOKINGS_FAILURE: 'BOOKINGS/CREATE/FAILURE',
    // bookings.controller - updateBooking
    UPDATE_BOOKINGS: 'BOOKINGS/UPDATE/REQUEST',
    UPDATE_BOOKINGS_SUCCESS: 'BOOKINGS/UPDATE/SUCCESS',
    UPDATE_BOOKINGS_FAILURE: 'BOOKINGS/UPDATE/FAILURE'
};
